_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/root/emtk_coal/ckpt/coco/base/model_reset_surgery.pth"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 62
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
    NAME: "CommonalityROIHeads"
    OUTPUT_LAYER: "DoubleFastRCNNOutputLayers"
    MEMORY: True
    AUGMENTATION: False
    SEMANTIC: True
    WARMUP_DISTILL: 600  #原始1000
DATASETS:
  TRAIN: ("removecoco14_trainval_all_5shot_seed0", )
  TEST: ('coBa_coal_test_all',)
  # TEST: ('coBa_coal_test_all_less',)
  TWO_STREAM: True
SOLVER:
  IMS_PER_BATCH: 4  #4
  BASE_LR: 0.005
  STEPS: (4000,)
  MAX_ITER: 4400
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/root/emtk/checkpoints/ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
  EVAL_PERIOD: 800  #800
OUTPUT_DIR: "/root/emtk_CoalForeign2/ckpt/cocoBaseForein/emtk_gfsod_novel/tfa-like/5shot_seed0"