_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/root/emtk_seeds/ckpt/coco/base/model_reset_surgery.pth"
  # WEIGHTS: "/root/emtk/checkpoints/coco/emtk_gfsod_novel/tfa-like/10shot_seed0/model_0005599.pth"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    NUM_CLASSES: 64
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
    NAME: "CommonalityROIHeads"
    OUTPUT_LAYER: "DoubleFastRCNNOutputLayers"
    MEMORY: True
    AUGMENTATION: False
    SEMANTIC: True
    WARMUP_DISTILL: 600
DATASETS:
  TRAIN: ("removecoco14_trainval_all_10shot_seed0", )
  TEST: ('coBa_coal_test_all',)
  TWO_STREAM: True
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.005
  STEPS: (4800,)
  MAX_ITER: 6500  #5600
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/root/emtk_seeds/pre_models/ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
  EVAL_PERIOD: 500
OUTPUT_DIR: "/root/emtk_seeds/ckpt/coco/emtk_gfsod_novel/tfa-like/10shot_seed0"