_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/root/emtk/checkpoints/voc/base2/model_reset_surgery.pth"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.001
    NUM_CLASSES: 20
    FREEZE_FEAT: True
    CLS_DROPOUT: True
    NAME: "CommonalityROIHeads"
    OUTPUT_LAYER: "DoubleFastRCNNOutputLayers"
    MEMORY: True
    AUGMENTATION: False
    SEMANTIC: True
    WARMUP_DISTILL: 200
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("removevoc_2007_trainval_all2_10shot_seed0", )
  TEST: ("voc_2007_test_all2",)
  TWO_STREAM: True
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (2000,)
  MAX_ITER: 2400
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "/root/emtk/checkpoints/ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
  EVAL_PERIOD: 20000
OUTPUT_DIR: "/root/emtk/checkpoints/voc/emtk_gfsod_novel2/tfa-like/10shot_seed0"